name       : gdk-pixbuf-xlib
version    : 2.40.2
release    : 2
source     :
    - https://gitlab.gnome.org/Archive/gdk-pixbuf-xlib/-/archive/2.40.2/gdk-pixbuf-xlib-2.40.2.tar.bz2 : 7d0e9f85e7a243e132f7420b253a7a57cea855f16aca58c3c42cdc9a4056df8e
license    : LGPL-2.1-only
component  : programming.library
summary    : DO NOT USE - Deprecated Xlib integration for GdkPixbuf
description: |
    DO NOT USE - Deprecated Xlib integration for GdkPixbuf
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(x11)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
